### ISSUE TITLE
build errors!

### ISSUE THREAD

**Issue by ra7ul** [cawka/ndnSIM-nom-rapid-car2car#4]
when I do what README says, it showed like below after the step'./waf': .
./src/ndnSIM/helper/ndn-global-routing-helper.cc:242:68: error: typedef ‘vertex_descriptor’ locally defined but not used [-Werror=unused-local-typedefs]
typedef graph_traits < NdnGlobalRouterGraph >::vertex_descriptor vertex_descriptor;
^
../src/ndnSIM/helper/ndn-global-routing-helper.cc: In static member function ‘static void ns3::ndn::GlobalRoutingHelper::CalculateAllPossibleRoutes()’:
../src/ndnSIM/helper/ndn-global-routing-helper.cc:332:68: error: typedef ‘vertex_descriptor’ locally defined but not used [-Werror=unused-local-typedefs]
typedef graph_traits < NdnGlobalRouterGraph >::vertex_descriptor vertex_descriptor;
^
cc1plus: all warnings being treated as errors
how should I do?

**Comment by cawka** [comment]
Given your compiler is overly cautious, you need to remove "-Werror" flag, which is always included during NS-3 compilation.  You can take solution from https://github.com/cawka/ns-3-dev-ndnSIM/commit/965856da98230e58a768dcd153405ee5051e63bf commit

**Comment by ra7ul** [comment]
Thank you for your nice reply! I have got 'build' finished successfully. But,  Im getting a new error after this, and I'm having a hard time figuring it out, it says 'OSError: [Errno 2] No such file or directory'.The whole messages as follows:
Traceback (most recent call last):
  File "/home/trokee/ra7ul/ndnSIM-nom-rapid-car2car-master/.waf-1.7.9-971322f1c53bc94dea5db65f5050b727/waflib/Scripting.py", line 97, in waf_entry_point
    run_commands()
  File "/home/trokee/ra7ul/ndnSIM-nom-rapid-car2car-master/.waf-1.7.9-971322f1c53bc94dea5db65f5050b727/waflib/Scripting.py", line 155, in run_commands
    run_command('shutdown')
  File "/home/trokee/ra7ul/ndnSIM-nom-rapid-car2car-master/.waf-1.7.9-971322f1c53bc94dea5db65f5050b727/waflib/Scripting.py", line 146, in run_command
    ctx.execute()
  File "/home/trokee/ra7ul/ndnSIM-nom-rapid-car2car-master/.waf-1.7.9-971322f1c53bc94dea5db65f5050b727/waflib/Context.py", line 87, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/trokee/ra7ul/ndnSIM-nom-rapid-car2car-master/.waf-1.7.9-971322f1c53bc94dea5db65f5050b727/waflib/Context.py", line 128, in recurse
    user_function(self)
  File "/home/trokee/ra7ul/ndnSIM-nom-rapid-car2car-master/wscript", line 108, in shutdown
    return subprocess.call (argv)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by ra7ul** [comment]
I have got the figures,I do appreciate your help! But,'OSError: [Errno 2] No such file or directory' is still here~
