### ISSUE TITLE
help!new error!

### ISSUE THREAD

**Issue by ra7ul** [cawka/ndnSIM-nom-rapid-car2car#5]
Thank you for your nice reply! I have got 'build' finished successfully. But, Im getting a new error after this, and I'm having a hard time figuring it out, it says 'OSError: [Errno 2] No such file or directory'.The whole messages as follows:
Traceback (most recent call last):
File "/home/trokee/ra7ul/ndnSIM-nom-rapid-car2car-master/.waf-1.7.9-971322f1c53bc94dea5db65f5050b727/waflib/Scripting.py", line 97, in waf_entry_point
run_commands()
File "/home/trokee/ra7ul/ndnSIM-nom-rapid-car2car-master/.waf-1.7.9-971322f1c53bc94dea5db65f5050b727/waflib/Scripting.py", line 155, in run_commands
run_command('shutdown')
File "/home/trokee/ra7ul/ndnSIM-nom-rapid-car2car-master/.waf-1.7.9-971322f1c53bc94dea5db65f5050b727/waflib/Scripting.py", line 146, in run_command
ctx.execute()
File "/home/trokee/ra7ul/ndnSIM-nom-rapid-car2car-master/.waf-1.7.9-971322f1c53bc94dea5db65f5050b727/waflib/Context.py", line 87, in execute
self.recurse([os.path.dirname(g_module.root_path)])
File "/home/trokee/ra7ul/ndnSIM-nom-rapid-car2car-master/.waf-1.7.9-971322f1c53bc94dea5db65f5050b727/waflib/Context.py", line 128, in recurse
user_function(self)
File "/home/trokee/ra7ul/ndnSIM-nom-rapid-car2car-master/wscript", line 108, in shutdown
return subprocess.call (argv)
File "/usr/lib/python2.7/subprocess.py", line 522, in call
return Popen(_popenargs, *_kwargs).wait()
File "/usr/lib/python2.7/subprocess.py", line 710, in init
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by ra7ul** [comment]
I think the reason is that I haven't get the input in the result.Right?

**Comment by maryam-eslahi** [comment]
hi, did u find the answer?
i really need to know about it.
tnx
